builds:
  - env:
      - CGO_ENABLED=0
      - BUILDKIT_PROGRESS=plain
    targets:
      - linux_amd64
      - darwin_amd64
      - linux_arm_7
    main: ./cmd/server

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

dockers:
  - image_templates:
      - "hmoragrega/fastlane:{{ .Version }}-linux-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "hmoragrega/fastlane:{{ .Version }}-linux-arm-v7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: hmoragrega/fastlane:{{ .Version }}
    image_templates:
      - hmoragrega/fastlane:{{ .Version }}-linux-amd64
      - hmoragrega/fastlane:{{ .Version }}-linux-arm-v7