name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    environment: Actions
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --debug --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_CLI_EXPERIMENTAL: enabled
      #-
      #  name: Set env
      #  run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      #-
      #  name: Build ARM image
      #  run: |
      #    cp dist/fastlane_linux_arm_7 ./fastlane \
      #    docker buildx build . --load -t hmoragrega/fastlane:${{ env.RELEASE_VERSION }}-linux-arm-v7 --platform=linux/arm/v7 \
      #    docker push hmoragrega/fastlane:0.0.1-rc14-linux-arm-v7 \
      #    docker ls -l dist/fastlane_linux_amd64
      #    ls -l dist/fastlane_linux_arm_7

